# -*- coding: utf-8 -*-
"""Projeto_Tabela_inicial .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xeIVUlc3G36rUzwi4pNCdrZvW7SvE7NA
"""

import os
import pandas as pd
import plotly.express as px

lista_arquivos = os.listdir("/content/drive/MyDrive/Vagas de TI/Vendas")
# mostra lista dos arquivos da pasta
print(lista_arquivos)
display(lista_arquivos)

#importar a base de dados de vendas
#arquivo é a variavel
#f antes do texto é para deixar o texto aceitando variaveis dinamicas

#tabela vazia
tabela_total = pd.DataFrame ()

for arquivo in lista_arquivos:
  if "Vendas" in arquivo:
    tabela = pd.read_csv(f"/content/drive/MyDrive/Vagas de TI/Vendas/{arquivo}")
    tabela_total = tabela_total.append(tabela)

tabela_produtos = tabela_total.groupby('Produto').sum()[['Quantidade Vendida','Preco Unitario']].sort_values(by="Quantidade Vendida", ascending= False)
display(tabela_produtos)

tabela_total['Faturamento'] = tabela_total['Quantidade Vendida'] * tabela_total['Preco Unitario']

tabela_faturamento = tabela_total.groupby('Produto').sum()[['Quantidade Vendida','Preco Unitario']].sort_values(by="Quantidade Vendida", ascending= False)

display(tabela_faturamento)

tabela_lojas = tabela_total.groupby('Loja').sum()[['Faturamento']]

display(tabela_lojas)

grafico = px.bar(tabela_lojas, x=tabela_lojas.index,y='Faturamento')
grafico.show()